<?php

namespace ContainerN9eCYcU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductsListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Listener\ProductsListener' shared autowired service.
     *
     * @return \App\Listener\ProductsListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Listener/ProductsListener.php';

        return $container->privates['App\\Listener\\ProductsListener'] = new \App\Listener\ProductsListener(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
